[Node.P2P]
StaticNodes = [
  "enode://9db67f8624bf651fa8d560e0abdd9635e9b27b2eb64844d607ba0265c0157738734c7fa90ee42200468e82f063ca42e1e5c61a00d288503e038cef33ecfa2924@35.236.66.130:30303",
  "enode://a5893e5634503a1223c15842a29788f1ef87e3a19f75664819b670afa8a326742e9b1a2c7507c45c2e74a85516fb210d30f76da8bdbda13db1f07aefb26825d1@35.228.164.134:30303",
  "enode://f9fec83c31e3e6ce92f99f92e38f7a7915d94ebc16edd3b352a8f2b21657822d5bd042dd039651e2f082520eaed82dac4e530a3076bce05f2545d001034abcc4@35.201.12.68:30303",

  "enode://02c2d10444a9aea86ed17674bb1d5b9d1c7bc94f89b74e245b6d17ed4a8eb5238b799df1371430be5fa0cdde48370501f52984f63c1be3cbae7521ea4bd09da4@35.236.46.111:30303",
  "enode://18eaf192a11c3ba56048a40cfc66a520fde4295d5d16b8fadfbd6c03a42ffe26e05f79a2630b2f0a6997ffe0c9d0ef5606e8e31de4d8f75125e8d6c858d53e56@35.245.74.240:30303",
  "enode://364f1c8b7ed18544c7582a7ac0cfd58e0a6b6836358fb1bbeae94559617579a0202e472808906bd5b710d2ce7efe0f24cd5524a8663526a8b3b83a5f22f8a77d@35.193.197.50:30303",
  "enode://d3cafe77d76e31aae25094aaede8a4b0f3e03679c2488373dee3a13f7f7b42dc82b8bf297b18c63d8d26ff7495355428d82ae9e08fb6610f4a2ed0ccb5ce055f@35.229.38.215:30303",
  "enode://62c3061d88d8b19cfc6b4037aa0cf1c192366651e2e8b285a62a6db4f11b07f279fdfb49c0bb7f0ecd2fef6028d8c1ab9816ecec7a79d1ab5564d5cd38451481@130.211.53.239:30303",
]
TrustedNodes = [
  "enode://9db67f8624bf651fa8d560e0abdd9635e9b27b2eb64844d607ba0265c0157738734c7fa90ee42200468e82f063ca42e1e5c61a00d288503e038cef33ecfa2924@35.236.66.130:30303",
  "enode://a5893e5634503a1223c15842a29788f1ef87e3a19f75664819b670afa8a326742e9b1a2c7507c45c2e74a85516fb210d30f76da8bdbda13db1f07aefb26825d1@35.228.164.134:30303",
  "enode://f9fec83c31e3e6ce92f99f92e38f7a7915d94ebc16edd3b352a8f2b21657822d5bd042dd039651e2f082520eaed82dac4e530a3076bce05f2545d001034abcc4@35.201.12.68:30303",

  "enode://02c2d10444a9aea86ed17674bb1d5b9d1c7bc94f89b74e245b6d17ed4a8eb5238b799df1371430be5fa0cdde48370501f52984f63c1be3cbae7521ea4bd09da4@35.236.46.111:30303",
  "enode://18eaf192a11c3ba56048a40cfc66a520fde4295d5d16b8fadfbd6c03a42ffe26e05f79a2630b2f0a6997ffe0c9d0ef5606e8e31de4d8f75125e8d6c858d53e56@35.245.74.240:30303",
  "enode://364f1c8b7ed18544c7582a7ac0cfd58e0a6b6836358fb1bbeae94559617579a0202e472808906bd5b710d2ce7efe0f24cd5524a8663526a8b3b83a5f22f8a77d@35.193.197.50:30303",
  "enode://d3cafe77d76e31aae25094aaede8a4b0f3e03679c2488373dee3a13f7f7b42dc82b8bf297b18c63d8d26ff7495355428d82ae9e08fb6610f4a2ed0ccb5ce055f@35.229.38.215:30303",
  "enode://62c3061d88d8b19cfc6b4037aa0cf1c192366651e2e8b285a62a6db4f11b07f279fdfb49c0bb7f0ecd2fef6028d8c1ab9816ecec7a79d1ab5564d5cd38451481@130.211.53.239:30303",
]
